//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _382Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int comment_id { get; set; }
        public Nullable<int> activity_id { get; set; }
        public string comment_include { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Users Users { get; set; }
    }
}
