//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _382Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public int like_id { get; set; }
        public Nullable<int> activity_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> good { get; set; }
        public Nullable<int> bad { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Users Users { get; set; }
    }
}
